export enum TaskType {
  APPROVER_TO_SENIOR_INVESTIGATOR = 'APPROVER => SI',
  SENIOR_INVESTIGATOR_TO_SENIOR_ANALYST = 'SI => SA',
  SENIOR_ANALYST_TO_ANALYST = 'SA => Analyst',
  SENIOR_INVESTIGATOR_TO_PRIVATE_INVESTIGATOR_LEAD = 'SI => PIL',
  PRIVATE_INVESTIGATOR_LEAD_TO_PRIVATE_INVESTIGATOR = 'PIL => PI',
}
